name: build electron
on:
  push:
    branches:
      - master
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install deps
        run: cd electron && npm install
      - name: Make package
        run: cd electron && npm run make
      - name: Upload deb
        uses: actions/upload-artifact@v2
        with:
          name: build-ubuntu-deb
          path: electron/out/make/deb
      - name: Upload rpm
        uses: actions/upload-artifact@v2
        with:
          name: build-ubuntu-rpm
          path: electron/out/make/rpm
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install deps
        run: cd electron && npm install
      - name: Make package
        run: cd electron && npm run make
      - uses: actions/upload-artifact@v2
        with:
          name: build-windows
          path: electron/out/make/exe
