name: build electron
on:
  push:
    branches:
      - master
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install deps
        run: cd electron && npm install
      - name: Make package
        run: cd electron && npm run package
      - uses: actions/upload-artifact@v2
        with:
          name: build-ubuntu
          path: electron/out
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install deps
        run: cd electron && npm install
      - name: Make package
        run: cd electron && npm run make
      - name: List
        run: cd electron/out && dir /s /b
      - uses: actions/upload-artifact@v2
        with:
          name: build-windows
          path: electron/out
